### ISSUE TITLE
Error with syntax

### ISSUE THREAD

**Issue by lITronusIl** [the-cult-of-integral/discord-raidkit#73] opened 2023-04-27 14:39 UTC
hi, i wanted to start the bot, but i got following output:
 File "/Discord Raidkit v2.4.1.py", line 41
27.04 14:37:14 [Bot] match option_id:
27.04 14:37:14 [Bot] ^
27.04 14:37:14 [Bot] SyntaxError: invalid syntax

how do i fix it?

**Comment by the-cult-of-integral** [comment] 2023-04-27 16:02
Closing for now - please reopen an issue if you think that the issue is persisting and is caused by non-external factors. @lITronusIl

**Closed by the-cult-of-integral** 2023-04-27 16:02 UTC
Labels: External
